config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # Index
  get "/", to: "home#index", as: "home"

  # List books
  get "/list", to: "list#index", as: "list_books"
  
  # Create book
  get "/add", to: "add#index", as: "add_book"
  post "/create", to: "add#create", as: "create_book"

  # Update book
  get "/edit/:id", to: "edit#index", as: "edit_book"
  post "/update/:id", to: "edit#update", as: "update_book"

  # Delete book
  delete "/remove/:id", to: "remove#delete", as: "remove_book"
end

app/models/book.rb
class Book 
    include Dynamoid::Document

    table name: :books, key: :id

    field :title, :string
    field :category, :string
    field :year, :string
end

app/controllers/add_controller.rb
class AddController < ApplicationController  
    add_flash_types :success, :warning, :error
    def create
        unless params[:title].present? && params[:category].present? && params[:year].present?
            return redirect_to add_book_path, warning: "Missing parameters."
        end

        book = Book.new(title: params[:title], category: params[:category], year: params[:year])

        if !book.save 
            return redirect_to add_book_path, error: "Error creating the book."
        end

        return redirect_to list_books_path, success: "You have successfully created the book with id: #{book.id}."
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/edit_controller.rb
class EditController < ApplicationController
    add_flash_types :success, :warning, :error
    def index
        @book = Book.find(params[:id])
    end

    def update
        unless params[:title].present? || params[:category].present? || params[:year].present?
            return redirect_to list_books_path, warning: "Missing parameters."
        end

        book = Book.find(params[:id])

        if params[:title]
            book.title = params[:title]
        end

        if params[:category]
            book.category = params[:category]
        end

        if params[:year]
            book.year = params[:year]
        end

        if !book.save 
            return redirect_to add_book_path, error: "Error updating the book."
        end

        return redirect_to list_books_path, success: "You have successfully updated the book id #{book.id}."
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  add_flash_types :notice, :warning

  def index
    @books = Book.all
  end
end

app/controllers/remove_controller.rb
class RemoveController < ApplicationController
    add_flash_types :success, :error
    def delete
        book = Book.find(params[:id])
        id = book.id
        
        if !book.delete 
            return redirect_to list_books_path, error: "Error removing the book."
        end

        return redirect_to list_books_path, success: "You have successfully removed the book id #{id}."
    end
end

app/helpers/add_helper.rb
module AddHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(type)
    case type
      when "notice" then "bg-blue-100 border-t border-b border-blue-500 text-blue-700 px-4 py-3"
      when "success" then "bg-green-100 border-t border-b border-green-500 text-green-700 px-4 py-3"
      when "error" then "bg-red-100 border-t border-b border-red-500 text-red-700 px-4 py-3"
      when "warning" then "bg-yellow-100 border-t border-b border-yellow-500 text-yellow-700 px-4 py-3"
    end
  end
end

app/helpers/edit_helper.rb
module EditHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/remove_helper.rb
module RemoveHelper
end

app/views/add/index.html.erb
<header class="p-4">
  <h1 class="text-2xl">Add book</h1>
</header>

<%= render partial: "shared/flash", locals: {flash: flash} %>

<section class="p-4">
  <%= render partial: 'forms/book', locals: {book: nil, path: create_book_path} %>
</section>

<div class="p-4">
  <%= render partial: "buttons/back", locals: {title: "Back to List", url: list_books_path } %>
</div>

app/views/buttons/_add.html.erb
<div class="my-4">
    <%= link_to title, url, class: "rounded-full text-center text-white p-2 transition duration-150 bg-green-600 hover:bg-green-400" %>
</div>

app/views/buttons/_back.html.erb
<div class="my-4">
    <%= link_to title, url, class: "rounded-full text-center text-white p-2 transition duration-150 bg-gray-600 hover:bg-gray-400" %>
</div>

app/views/edit/index.html.erb
<header class="p-4">
  <h1 class="text-2xl">Edit book</h1>
</header>

<%= render partial: "shared/flash", locals: {flash: flash} %>

<section class="p-4">
  <%= render partial: 'forms/book', locals: {book: @book, path: update_book_path} %>
</section>

<div class="p-4">
  <%= render partial: "buttons/back", locals: {title: "Back to List", url: list_books_path } %>
</div>

app/views/forms/_book.html.erb
<%= form_with :url => path do |form| %>
  <%= form.label :title, class: "block text-gray-700 text-sm font-bold mb-2" %>
  <%= 
    form.text_field :title, 
    value: book ? book.title : '',
    placeholder: "Type the Title of the book", 
    class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
  %>

  <%= form.label :category, class: "block text-gray-700 text-sm font-bold mb-2" %>
  <%= 
    form.text_field :category, 
    value: book ? book.category : '',
    placeholder: "Type the Category of the book", 
    class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" 
  %>

  <%= form.label :year, class: "block text-gray-700 text-sm font-bold mb-2" %>
  <%= 
    form.text_field :year, 
    value: book ? book.year : '',
    placeholder: "Type the Year of the book", 
    class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" 
  %>

  <div class="flex items-center justify-between my-4">
    <%= form.submit class: "rounded-full text-center text-white p-2 transition duration-150 bg-green-600 hover:bg-green-400" %>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="container mx-auto">
    <header class="p-4">
        <h1 class="text-center text-2xl">Library Application</h1>
    </header>

    <section class="p-4 mx-auto max-w-lg">
        <div class="grid grid-cols-2">
            <%= link_to "List", list_books_path, class: "rounded-full text-center text-white p-2 m-2 transition duration-150 bg-blue-600 hover:bg-blue-400" %>
            <%= link_to "Add", add_book_path, class: "rounded-full text-center text-white p-2 m-2 transition duration-150 bg-green-600 hover:bg-green-400" %>
        </div>
    </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 antialiased">
      <%= yield %>
    </main>
  </body>
</html>

app/views/list/_table.html.erb
<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
  <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
      <tr>
        <th scope="col" class="px-6 py-3">
          Title
        </th>
        <th scope="col" class="px-6 py-3">
          Category
        </th>
        <th scope="col" class="px-6 py-3">
          Year
        </th>
        <th scope="col" class="px-6 py-3">
          <span class="sr-only">Edit</span>
        </th>
      </tr>
    </thead>
    <tbody>
      <% books.each do |book| -%>
        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
          <th scope="row" class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
            <%= book.title %>
          </th>
          <td class="px-6 py-4">
            <%= book.category %>
          </td>
          <td class="px-6 py-4">
            <%= book.year %>
          </td>
          <td class="px-6 py-4 text-right">
            <%= link_to "Edit", edit_book_path(id: book.id), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
            <%= link_to "Delete", remove_book_path(id: book.id), method: :delete, class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
          </td>
        </tr>
      <% end -%>
    </tbody>
  </table>
</div>

app/views/list/index.html.erb
<header class="p-4">
    <h1 class="text-2xl">Book list</h1>
</header>

<%= render partial: "shared/flash", locals: {flash: flash} %>

<div class="p-4">
  <%= render partial: "buttons/add", locals: {title: "Add book", url: add_book_path } %>
</div>

<section class="p-4">
  <%= render partial: 'table', locals: {books: @books} %>
</section>

<div class="p-4">
  <%= render partial: "buttons/back", locals: {title: "Back to Home", url: home_path } %>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="<%= flash_class(type).to_s %>" role="alert">
    <p class="font-bold"><%= type.capitalize  %></p>
    <p class="text-sm"><%= msg %></p>
  </div>
<% end %>